### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by ahousing** [kaazing/gateway.truststore#5]
Recently, the parent in pom.xml was updated to point to community.  Since then, the builds have failed.

**Comment by dpwspoon** [comment]
Its been moved to jenkins and is passing.  I disabled the bamboo plan.  It could probably be deleted

**Comment by dpwspoon** [comment]
Assigning back to you Art to figure out what to do with the bamboo plan

**Comment by ahousing** [comment]
I was 50/50 on disabling (since it's in the "move the jenkins" section) and moving to a new place (Z - Obsolete).  I ended up going with the latter.
